import type { Metadata } from 'next';
import {
  Geist, Geist_Mono, Poppins,
} from 'next/font/google';

import './globals.css';
import ApolloWrapper from './components/Apollo/ApolloWrapper';

const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
});

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: [
    '300',
    '400',
    '500',
    '600',
    '700',
  ],
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        <ApolloWrapper>
          {children}
        </ApolloWrapper>
      </body>
    </html>
  );
}
